// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NaumovStomKlin.API.Data;

#nullable disable

namespace NaumovStomKlin.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517155719_UpdateAppointmentTable12")]
    partial class UpdateAppointmentTable12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NaumovStomKlin.API.Models.Appointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("appointment_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("doctor_id")
                        .HasColumnType("int");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("doctor_id");

                    b.HasIndex("patient_id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.Appointment_procedure", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("appointment_id")
                        .HasColumnType("int");

                    b.Property<int?>("appointmentid")
                        .HasColumnType("int");

                    b.Property<int>("procedure_id")
                        .HasColumnType("int");

                    b.Property<int?>("procedureid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("appointmentid");

                    b.HasIndex("procedureid");

                    b.ToTable("Appointment_procedurs");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.Procedure", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("Procedurs");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.Appointment", b =>
                {
                    b.HasOne("NaumovStomKlin.API.Models.User", "doctor")
                        .WithMany("appointments_as_doctor")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NaumovStomKlin.API.Models.User", "patient")
                        .WithMany("appointments_as_patient")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.Appointment_procedure", b =>
                {
                    b.HasOne("NaumovStomKlin.API.Models.Appointment", "appointment")
                        .WithMany("appointment_procedures")
                        .HasForeignKey("appointmentid");

                    b.HasOne("NaumovStomKlin.API.Models.Procedure", "procedure")
                        .WithMany("appointment_procedures")
                        .HasForeignKey("procedureid");

                    b.Navigation("appointment");

                    b.Navigation("procedure");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.User", b =>
                {
                    b.HasOne("NaumovStomKlin.API.Models.Role", "role")
                        .WithMany("users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.Appointment", b =>
                {
                    b.Navigation("appointment_procedures");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.Procedure", b =>
                {
                    b.Navigation("appointment_procedures");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.Role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("NaumovStomKlin.API.Models.User", b =>
                {
                    b.Navigation("appointments_as_doctor");

                    b.Navigation("appointments_as_patient");
                });
#pragma warning restore 612, 618
        }
    }
}
