version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dental-backend
    ports:
      - "7057:7057"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7057
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: dental-frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dental-db
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: