FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 7057

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["NaumovStomKlin.API/NaumovStomKlin.API.csproj", "NaumovStomKlin.API/"]
RUN dotnet restore "NaumovStomKlin.API/NaumovStomKlin.API.csproj"

COPY . .
WORKDIR "/src/NaumovStomKlin.API"
RUN dotnet build "NaumovStomKlin.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NaumovStomKlin.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NaumovStomKlin.API.dll"]